### PR TITLE
Added minimal dotnetcore cases and small improvements

### PR DESCRIPTION
**Pull request by mcliment**
To be fair, using MVC to return a JSON is too much and I was curious to know the performance hit of MVC by removing it and using only routing.
On the other hand I did some cleanup of the project.json files and a small improvement in the third case as the list of countries was created on every request.

### CODE REVIEW

**Comment by erinus** [comment]
@mcliment Thanks for your advice. I actually write a lot of improper code. I will take your modification and re-run performance test to gain the new record. It need 2 ~ 3 days.

**Comment by mcliment** [comment]
Take your time, I found your repository by chance and wanted to add some extras.

**Comment by erinus** [comment]
@mcliment I modified 'Case 01' and re-run test.

Throughput of .Net Core: 16299 -> 16324

I commited all modified code of 'Case 01'. Do I have any improper code? Thanks.

**Comment by erinus** [comment]
@mcliment To be fair, I replaced Newtonsoft.Json by System.Runtime.Serialization.Json.DataContractJsonSerializer (built-in Json Serializer) for 'Case 01' and 'Case 02'.

I will add 'Newtonsoft.Json' test in the next move.

**Comment by mcliment** [comment]
Fine, but bear in mind that Newtonsoft is the default serializer for MVC (https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json)

**Comment by erinus** [comment]
@mcliment Thanks for your information. I will add this note in README.md.

**Pull request merged**
